# Generated by Django 4.2.10 on 2026-01-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hudra_tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="task",
            name="category",
        ),
        migrations.RemoveField(
            model_name="task",
            name="location",
        ),
        migrations.RemoveField(
            model_name="task",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="task",
            name="reward",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("posted", "Posted"),
                    ("assigned", "Assigned"),
                    ("completed", "Completed"),
                    ("paid", "Paid"),
                ],
                default="posted",
                max_length=20,
            ),
        ),
    ]
