# Generated by Django 4.2.10 on 2026-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hudra_tasks", "0003_remove_task_assignee_remove_task_poster_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="reward",
            new_name="budget",
        ),
        migrations.RemoveField(
            model_name="task",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_paid",
        ),
        migrations.AddField(
            model_name="task",
            name="location",
            field=models.CharField(default="Unknown", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
